using System;
using UnityEngine;
using UnityEngine.UIElements;
using Workshop.UI_And_Tools.Forge.Builders.GuiBuilders;

namespace Assets.Scripts.Fractals
{
    public class BurningShipLoreProvider : IGuiProvider
    {
        public string Title => "THE BURNING SHIP";
        private FractalForgeContext _ctx;

        public BurningShipLoreProvider(FractalForgeContext ctx) { _ctx = ctx; }

        public VisualElement CreateGui(GuiContext guiCtx)
        {
            _ctx.CurrentFormula = FractalFormula.BurningShip;
            _ctx.ViewContext.IsDirty = true;

            var root = new ForgeContainerBuilder("BurningShipLore")
                .WithDirection(FlexDirection.Column).WithPadding(15)
                .AddChild(new ForgeLabelBuilder("NON-ANALYTIC CHAOS")
                    .WithColor(new Color(1.0f, 0.4f, 0.0f)).WithFontSize(22).WithBold().WithMarginBottom(10)) // Orange for burning ship

                .AddChild(new ForgeLabelBuilder("Discovered in 1992, the Burning Ship is generated by taking the absolute value of the real and imaginary components of Z *before* they are squared: Z = (|Re(Z)| + i|Im(Z)|)^2 + C.")
                    .WithColor(new Color(0.8f, 0.8f, 0.8f)).WithWhiteSpace(WhiteSpace.Normal).WithMarginBottom(10))
                .AddChild(new ForgeLabelBuilder("Because the absolute value function is 'non-analytic' (it doesn't have a smooth derivative everywhere), it violently folds the mathematical space over the X and Y axes. This destroys the elegant, organic spirals of the Mandelbrot set and replaces them with rigid, architectural, mast-like structures that resemble a ghost armada.")
                    .WithColor(new Color(0.6f, 0.6f, 0.6f)).WithWhiteSpace(WhiteSpace.Normal).WithMarginBottom(20))

                .AddChild(new ForgeLabelBuilder("AESTHETIC LABORATORY")
                    .WithColor(Color.green).WithBold().WithMarginBottom(10))

                .OnBuild(ve =>
                {
                    // Parameter: Color Stretching (Non-linear distribution)
                    // The burning ship often needs severe color stretching to see the "flames"
                    var stretchLabel = new Label($"Atmospheric Density (Color Stretch): {_ctx.ColorStretch:F2}") { style = { color = Color.cyan } };
                    var stretchSlider = new Slider(0.01f, 3.0f) { value = _ctx.ColorStretch };
                    stretchSlider.RegisterValueChangedCallback(evt => {
                        _ctx.ColorStretch = evt.newValue;
                        stretchLabel.text = $"Atmospheric Density (Color Stretch): {_ctx.ColorStretch:F2}";
                        _ctx.ViewContext.IsDirty = true;
                    });
                    ve.Add(stretchLabel); ve.Add(stretchSlider);
                });

            return root.Build();
        }

        public Action<VisualElement> GetGuiBuilder() => root => root.Add(CreateGui(new GuiContext()));
        public void ToUIDocument(string path) { }
        public void FromUIDocument(string path) { }
    }
}