using System;
using UnityEngine;
using UnityEngine.UIElements;
using Workshop.UI_And_Tools.Forge.Builders.GuiBuilders;

namespace Assets.Scripts.Fractals
{
    public class TricornLoreProvider : IGuiProvider
    {
        public string Title => "THE TRICORN";
        private FractalForgeContext _ctx;

        public TricornLoreProvider(FractalForgeContext ctx) { _ctx = ctx; }

        public VisualElement CreateGui(GuiContext guiCtx)
        {
            _ctx.CurrentFormula = FractalFormula.Tricorn;
            _ctx.ViewContext.IsDirty = true;

            var root = new ForgeContainerBuilder("TricornLore")
                .WithDirection(FlexDirection.Column).WithPadding(15)
                .AddChild(new ForgeLabelBuilder("THE ANTI-POLYNOMIAL")
                    .WithColor(Color.cyan).WithFontSize(22).WithBold().WithMarginBottom(10))

                .AddChild(new ForgeLabelBuilder("Discovered in 1989, the Tricorn (or Mandelbar) is generated by taking the complex conjugate of Z before squaring it: Z = conj(Z)^2 + C. The conjugate flips the sign of the imaginary part every single iteration.")
                    .WithColor(new Color(0.8f, 0.8f, 0.8f)).WithWhiteSpace(WhiteSpace.Normal).WithMarginBottom(10))
                .AddChild(new ForgeLabelBuilder("This continuous inversion prevents the math from forming the smooth, circular bulbs found in the Mandelbrot set. Instead, the topology fractures into sharp, three-cornered 'swallowtail' bifurcations. Deep zooming reveals severe mathematical distortions and isolated islands disconnected from the main body.")
                    .WithColor(new Color(0.6f, 0.6f, 0.6f)).WithWhiteSpace(WhiteSpace.Normal).WithMarginBottom(20))

                .AddChild(new ForgeLabelBuilder("MATHEMATICAL LABORATORY")
                    .WithColor(Color.green).WithBold().WithMarginBottom(10))

                .OnBuild(ve =>
                {
                    var iterLabel = new Label($"Escape Horizon (Max Iterations): {_ctx.MaxIterations}") { style = { color = Color.cyan } };
                    var iterSlider = new SliderInt(10, 1500) { value = _ctx.MaxIterations };
                    iterSlider.RegisterValueChangedCallback(evt => {
                        _ctx.MaxIterations = evt.newValue;
                        iterLabel.text = $"Escape Horizon (Max Iterations): {_ctx.MaxIterations}";
                        _ctx.ViewContext.IsDirty = true;
                    });
                    ve.Add(iterLabel); ve.Add(iterSlider);
                });

            return root.Build();
        }

        public Action<VisualElement> GetGuiBuilder() => root => root.Add(CreateGui(new GuiContext()));
        public void ToUIDocument(string path) { }
        public void FromUIDocument(string path) { }
    }
}