using System;
using UnityEngine;
using TheSingularityWorkshop.FSM_API;

namespace Assets.Scripts.MastersOfOrionII.Economy
{
    public enum FirmOriginEvent
    {
        StandardIncorporation,
        MilitarySpinoff,
        AccidentalDiscovery,
        HostileTakeover,
        BlackMarketLegitimacy
    }

    public class ContractFirm : MonoBehaviour, IStateContext
    {
        public bool IsValid { get; set; } = true;
        public string Name { get; set; } = "Corporation";
        public string TickerSymbol { get; set; } = "UNK";

        // --- VISUAL IDENTITY ---
        public Texture2D FirmLogo { get; set; }

        // --- IDENTITY & RELATIONS ---
        public string CEO { get; set; } = "Unknown Board";
        public GalacticIndustry PrimaryIndustry { get; set; }
        public RegionalExchange HomeExchange { get; set; }

        // --- LORE & WFC ARCHITECTURE ---
        public FirmOriginEvent Origin { get; set; } = FirmOriginEvent.StandardIncorporation;
        public string FoundingHistory { get; set; } = "";

        // If false, it is a ghost generated by Squirrel3. If true, it is ticking in the FSM.
        public bool IsPersistent { get; set; } = false;

        // --- MACRO ECONOMICS ---
        public long EmployeeCount { get; set; } = 1000;
        public double LiquidCapital { get; set; } = 5000000;
        public float CurrentStockPrice { get; set; } = 15.50f;
        public long OutstandingShares { get; set; } = 1000000;
        public double MarketCap => CurrentStockPrice * OutstandingShares;

        // --- ENGINEERING LOGISTICS ---
        public float MonthlyProductionCapacity { get; set; } = 50000f;
        public float ActiveContractVolume { get; set; } = 0f;
        public float PerformanceMultiplier { get; set; } = 1.0f;

        // ====================================================================
        // THE MICRO-ECONOMY FSM ENGINE
        // ====================================================================
        public void Initialize()
        {
            if ( !FSM_API.Interaction.Exists("FirmBusinessCycle", "MicroEconomyTick"))
            {
                FSM_API.Create.CreateFiniteStateMachine("FirmBusinessCycle", -1, "MicroEconomyTick")
                    .State("SeekingContracts", null, OnUpdateSeeking, null)
                    .State("ActiveProduction", null, OnUpdateProduction, null)
                    .State("Insolvent", OnEnterInsolvent, null, null)

                    // Natural business flow
                    .Transition("SeekingContracts", "ActiveProduction", ctx => ((ContractFirm)ctx).ActiveContractVolume > 0)
                    .Transition("ActiveProduction", "SeekingContracts", ctx => ((ContractFirm)ctx).ActiveContractVolume <= 0)

                    // Bankruptcy check
                    .Transition("SeekingContracts", "Insolvent", ctx => ((ContractFirm)ctx).LiquidCapital <= 0)
                    .Transition("ActiveProduction", "Insolvent", ctx => ((ContractFirm)ctx).LiquidCapital <= 0)
                    .BuildDefinition();
            }
            FSM_API.Create.CreateInstance("FirmBusinessCycle", this, "MicroEconomyTick");
        }

        private static void OnUpdateSeeking(IStateContext context)
        {
            var firm = (ContractFirm)context;
            if (!firm.IsPersistent) return; // Ephemeral ghosts don't drain capital

            // Operating costs drain capital when no contracts are active
            firm.LiquidCapital -= (firm.MonthlyProductionCapacity * 0.01f);
        }

        private static void OnUpdateProduction(IStateContext context)
        {
            var firm = (ContractFirm)context;
            if (!firm.IsPersistent) return;

            // Fulfilling the player's ship order!
            float processingRate = firm.MonthlyProductionCapacity * 0.1f; // Amount processed this tick
            firm.ActiveContractVolume -= processingRate;

            // They get paid for work done, boosting liquid capital and driving up stock price
            double profit = processingRate * 15.0;
            firm.LiquidCapital += profit;

            // Positive earnings report boosts stock instantly
            if (profit > 0) firm.CurrentStockPrice *= 1.0005f;

            if (firm.ActiveContractVolume < 0) firm.ActiveContractVolume = 0;
        }

        private static void OnEnterInsolvent(IStateContext context)
        {
            var firm = (ContractFirm)context;
            firm.CurrentStockPrice = 0.01f;
            Debug.LogWarning($"[Market Alert] {firm.Name} ({firm.TickerSymbol}) has filed for bankruptcy. All active player contracts suspended.");
        }
    }
}