using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;
using Workshop.UI_And_Tools.Showcase;


namespace Workshop.EditorTools
{
    public class ShowcaseRegistryGenerator : IPreprocessBuildWithReport
    {
        public int callbackOrder => 0; // Run first in the build pipeline

        // Automatically runs when you hit "Build"
        public void OnPreprocessBuild(BuildReport report)
        {
            Debug.Log("[ShowcaseGenerator] Build started. Generating Static Registry...");
            GenerateRegistry();
        }

        // Add a menu item so you can force-generate it during development without building
        [MenuItem("The Forge/Code Generation/Generate Showcase Registry")]
        public static void GenerateRegistry()
        {
            var interfaceType = typeof(IShowcasePortal);

            // 1. Reflect to find all portals (Editor Only, perfectly safe!)
            var portalTypes = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(s => s.GetTypes())
                .Where(p => interfaceType.IsAssignableFrom(p) && !p.IsInterface && !p.IsAbstract)
                .ToList();

            // 2. Begin writing the C# file
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// ===========================================================================");
            sb.AppendLine("// AUTO-GENERATED BY THE FORGE CODE GENERATOR.");
            sb.AppendLine("// DO NOT EDIT MANUALLY. CHANGES WILL BE OVERWRITTEN ON THE NEXT BUILD.");
            sb.AppendLine("// ===========================================================================");
            sb.AppendLine();
            sb.AppendLine("using Workshop.UI_And_Tools.Showcase;");
            sb.AppendLine();
            sb.AppendLine("namespace Workshop.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class StaticShowcaseRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static void InjectAllPortals()");
            sb.AppendLine("        {");

            // 3. Inject the explicit constructors
            int count = 0;
            foreach (var type in portalTypes)
            {
                // FullName ensures we don't have namespace collision issues
                sb.AppendLine($"            ExperienceRegistry.RegisterManual(new {type.FullName}());");
                count++;
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            // 4. Save the file to a specific Runtime folder
            string directoryPath = "Assets/Scripts/Workshop/Generated";
            if (!Directory.Exists(directoryPath)) Directory.CreateDirectory(directoryPath);

            string filePath = Path.Combine(directoryPath, "StaticShowcaseRegistry.cs");
            File.WriteAllText(filePath, sb.ToString());

            // 5. Force Unity to compile the newly created script
            AssetDatabase.Refresh();
            Debug.Log($"[ShowcaseGenerator] Successfully hard-coded {count} Portals into StaticShowcaseRegistry.cs");
        }
    }
}