using UnityEngine;
using UnityEngine.UIElements;
using Workshop.Generated;
using Workshop.UI_And_Tools.Forge.Builders.GuiBuilders;
using Workshop.UI_And_Tools.Forge.Builders.Staging;
using Workshop.UI_And_Tools.Showcase;

namespace Workshop.WebGl
{
    [RequireComponent(typeof(UIDocument))]
    public class WebGL_Bootstrapper : MonoBehaviour
    {
        private void Start()
        {
            // 1. INJECT THE GENERATED CODE
            // IL2CPP traces this method, sees all the 'new' keywords, and protects your code!
            StaticShowcaseRegistry.InjectAllPortals();

            // 2. HIJACK THE UI DOCUMENT
            var document = GetComponent<UIDocument>();
            var root = document.rootVisualElement;

            // Clear the single element or anything else Unity tried to put there
            root.Clear();

            // Force absolute ownership of the DOM/Screen at the root level.
            // This tells Unity's layout engine that this element is the definitive boundary.
            root.style.position = Position.Absolute;
            root.style.top = 0;
            root.style.left = 0;
            root.style.right = 0;
            root.style.bottom = 0;
            root.style.width = new Length(100, LengthUnit.Percent);
            root.style.height = new Length(100, LengthUnit.Percent);
            root.style.paddingTop = 0;
            root.style.paddingBottom = 0;
            root.style.paddingLeft = 0;
            root.style.paddingRight = 0;
            root.style.marginTop = 0;
            root.style.marginBottom = 0;
            root.style.marginLeft = 0;
            root.style.marginRight = 0;

            // 3. BOOT THE LOBBY
            var lobby = new Showcase_SingularityLobby(null);
            var ctx = new GuiContext { Name = "WebGL_Runtime", EditMode = false };

            var generatedUI = lobby.CreateGui(ctx);

            // Ensure the generated UI flex-grows to consume our newly constrained absolute root
            generatedUI.style.flexGrow = 1;
            generatedUI.style.position = Position.Absolute;
            generatedUI.style.top = 0;
            generatedUI.style.left = 0;
            generatedUI.style.width = new Length(100, LengthUnit.Percent);
            generatedUI.style.height = new Length(100, LengthUnit.Percent);
            root.Add(generatedUI);

            Debug.Log("[WebGL_Bootstrapper] Screen hijacked. Lobby injected.");
        }

        private void Awake()
        {
            Debug.Log("[WebGL_Bootstrapper] Executing Auto-Generated Portal Injection...");

            // THIS is the magic bullet. It runs the hardcoded instantiations
            // generated by your MetaDev tool, bypassing IL2CPP stripping.
            StaticShowcaseRegistry.InjectAllPortals();
        }
    }
}